<a href="https://colab.research.google.com/github/AElias10/AElias10/blob/main/list%26DataFrame%26/Dic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ejercicio 1: Determina si un número es divisible por 3 y por 5 💡** / TAREA

In [ ]:

#EJERCICIO 1

num=int(input("Ingrese un número:"))

rta=0
div_1=3
div_2=5
rta_1=num/div_1
rta_2=num/div_2

if num % div_1==0:
  print("El número",num,"es divisible por",div_1)

if num % div_2==0:
  print("El número",num,"es divisible por",div_2)

if num % div_1==0 and num % div_2==0:
  print("Es divisible por ambos")




Ingrese un número:15
El número 15 es divisible por 3
El número 15 es divisible por 5
Es divisible por ambos


Ejercicio 2: Calcula el residuo de la división de un número por 7 y verifica si es igual a 3

In [ ]:
#operadores

# % modulo
# ** exponente
# != diferente


#EJERCICIO 2

#dividir por 7 y resto=3

#divisor:nro q divide al dividendo

#ejemplo nro 10,17,24

#inicialización
dividendo=0
resto=0
divisor=7


dividendo=int(input("Ingrese dividendo:"))
rta=dividendo/divisor
print("El resultado es:",round(rta,2))
resto=dividendo % divisor
if resto==3:
  print("El residuo es igual a: 3")
else:
  print("El resto es :",resto,"el cual es diferente a 3")





Ingrese dividendo:7
El resultado es: 1.0
El resto es : 0 el cual es diferente a 3


**Ejercicio 3: Eleva un número al cuadrado, suma 10 y verifica si el resultado es mayor que 50  💡** (RECORDAR QUE EL CUADRADO SE ESCRIBE CON **)

In [ ]:

#EJERCICIO 3

num=0
suma=10
res=50
num=int(input("Ingrese un número:"))
if (num**2)+suma > res:
  print("El resultado es:",(num**2)+suma,"y es mayor a",res)
else:
  print("El resultado es:",(num**2)+suma, "y no es mayor a",res)




Ingrese un número:25
El resultado es: 635 y es mayor a 50


**Ejercicio 4: 📊 Calcula el producto de dos números y verifica si el resultado es menor que 20**

In [ ]:

#EJERCICIO 4

num_1=0
num_2=0

num_1=int(input("Ingrese un número:"))
num_2=int(input("Ingrese otro número:"))
prod=num_1*num_2
if prod <20:
  print("El resultado del producto de",num_1,"*",num_2,"es:",prod,"y es menor que 20")
else:
  print("El resultado del producto de",num_1,"*",num_2,"es:",prod,"y es mayor que 20")





Ingrese un número:2
Ingrese otro número:3
El resultado del producto de 2 * 3 es: 6 y es menor que 20


Ejercicio 5: 🎲 Calcula el área de un círculo con radio 5 y verifica si es mayor que 50.

In [ ]:

#EJERCICIO 5

#Area= pi*r**2

pi=3.14
r=5
print("Radio:",r)
area=0
area=pi*r**2
if area>50:
  print("El área del círculo es:",area,"y es mayor que 50")
else:
  print("El área del círculo es:",area,"y es menor a 50")


Radio: 5
El área del círculo es: 78.5 y es mayor que 50


FUNCIÓN// Ejercicio Doble Divertido

In [ ]:

def doble(n1):
  n1=n1*2
  return n1

num_doble=0
n1=int(input("Ingrese un número:"))
num_doble= doble(n1) #se asigna a la variable num_doble
                     #valor de funcion def doble(n1):
print(num_doble)






Ingrese un número:4
8


¡Vamos a calcular el cuadrado de un número! Tu tarea es escribir una función que tome un número y devuelva su cuadrado.

In [ ]:

def calcular_cuadrado(num):
  num=num**2



num=int(input("Ingrese un número:"))
print("El resultado es:",calcular_cuadrado(num))







Ingrese un número:2
El resultado es: None


Potencia del Cubo

In [ ]:

#potencia del cubo


def cubo(n3):
  res=n3**3
  return res

n3=int(input("Ingrese un número:"))
print("El resultado es:",cubo(n3))



***Pandas & Numpy***

In [ ]:

#Librería Numpy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# df.shape tamaño del dataframe
# df.head() muestra las primeras 5 filas head(n) muestra las n filas
# df.tail() muestra los 5 últimos  tail(n) últimas n filas
#df.sort_values() orden ascendente //// descendente--> df.sort_values("variable", ascending=False)
#df[["columna_1","columna_2"]]
#df[["fila_1","fila_2"]]
#df[:n] --> devielve las primeras n filas
#df.iloc[[4,10],[0,2]] columna 4 y 10 , fila 0 y 2
#df[df["longitud_sepalo"]>5 & (df[longitud_sepalo]>1.4)]
#df["longitud_sepalo"]-df["longitud_petalo"]  #resta de columnas
#df["ancho_sepalo"].apply(lamda x: -x) convierte valores en (-)
#df["ancho_sepalo"].apply(lamda x: x**2) eleva al cuadrado
#df.groupby("clase")["ancho_petalo"].mean() media
#df_group.name=",media_ancho_petalo" mostrar--> df_group

#import matplotlib.pyplot as plt
#df_join ["media_ancho_petalo"].plot() #graphics



#serie= pd.Series(["1","2","3"])
#serie.name='Tabla'
#serie
df= pd.DataFrame({"Calificación":[""],"Calificación 2":[""],"Calificación 3":[""],"Promedio":[""]})
df=df.append({"Nombre":"Elías"}, ignore_index=True)






EJERCICIOS LISTAS

***NUMPY***

In [ ]:

import numpy as np
#arrary 1D

array=np.array=([1,2,3])
print("El array es:",array)
print("----------------------------")

#matrix zeros

matrix_zeros=np.zeros([3,3])
print("\nLa matriz es:\n",matrix_zeros)
print("----------------------------")

#matrix identidad 4x4

matrix_identidad=np.eye(4)
print("\nMatriz identidad:\n",matrix_identidad)

print("----------------------------")

#suma de dos matrices

print("\nSuma de dos matrices:\n")
matrix_1=np.array=([1,2,],[4,3])
matrix_2=np.array=([9,4,],[3,1])
matrix_addition=np.add(matrix_1,matrix_2)
print(matrix_addition)
print("----------------------------")

#otro método

print("Otro método de suma de matrices")
matrix_c=np.array=([1,2],[4,8])
matrix_d=np.array=([9,7],[8,3])
matrix_addition_2=np.add(matrix_c,matrix_d)
print(matrix_addition_2)

#producto de matrices

matrix_e=np.array=([1,2],[3,4])
matrix_f=np.array=([5,6],[7,8])
matrix_product=np.dot(matrix_e,matrix_f)
print(matrix_product)





El array es: [1, 2, 3]
----------------------------

La matriz es:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------------------------

Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----------------------------

Suma de dos matrices:

[[10  6]
 [ 7  4]]
----------------------------
Otro método de suma de matrices
[[10  9]
 [12 11]]
[[19 22]
 [43 50]]


DataFrames

In [ ]:
import pandas as pd

#df[["columna_1","columna_2"]]
#df[["fila_1","fila_2"]]

#crear un DataFrame ej:
planilla=["Nombre","Apellido","Nota 1"]
print(planilla)





['Nombre', 'Apellido', 'Nota 1']


In [ ]:

#EJERCCIO 1.21 PDF

#Crear una lista con los días de la semana
#Eliminar de la lista el sábado y el
#domingo
#Mostrar el contenido de la lista

list=["Lunes","Martes","Miercoles","Jueves","Viernes","Sábado","Domingo"]
list_2=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio"]
print(list)
print(list_2)

#eliminar posit[5] luego para eliminar posit[6]("este ahora esta en posit[5]")
#por eso se eliminan ambos con igual índice
print("Eliminar elementos con función","del list[]")
del list[5]
del list[5]
print(list)

print("-----------------------------------------------------------------")
print("Otro Método pop()")

list_2.pop(6)
list_2.pop(5)
print(list_2)




['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio']
Eliminar elementos con función del list[]
['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes']
-----------------------------------------------------------------
Otro Método pop()
['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo']


EJERCICIOS LISTAS

In [ ]:

#EJERCICIO 1.22 PDF

#Crear una lista l1 con todos los días de la
#semana
#Imprimir la longitud de l1
#Extender l1 con si misma
#Imprimir la longitud de l1


#list=["Lunes","Martes","Miercoles","Jueves","Viernes","Sábado","Domingo"]
#print(list)

#print("El tamaño de la lista es:",len(list))

##OPERACIONES CON LISTAS ##

l1=[4,5,6]
l2=[9,4,2]
l3=[]

##SUMA
l3=(zip(l1,l2))
l4=[x1+x2 for (x1,x2) in l3]
print(l4)





[13, 9, 8]


EJERCICIO TUPLA


In [ ]:

#EJERCICIO 1.26  PDF


#Buscar día Domingo en tupla
semana=("Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo")

if "Domingo" in semana:
  print("El día Domingo está en la tupla")
else:
  print("El día Domingo no está en la tupla")

#recorrer e imprimir día x día
for i in semana:
  print(i)



El día Domingo está en la tupla
Lunes
Martes
Miercoles
Jueves
Viernes
Sábado
Domingo


EJERCICIO DICCIONARIOS


In [ ]:

#EJERCICIO 1.38 DICCIONARIOS

#Crear una diccionario d con todos los
#días de la semana poniendo como clave
#las siete primeras letras del alfabeto
#Imprimir el diccionario

diccionario={"Llave":"Valor"}
print(diccionario['Llave'])
print(diccionario)



dic={"LUNES":"L","MARTES":"M","MIÉRCOLES":"MM","JUEVES":"J","VIERNES":"V","SÁBADO":"S","DOMINGO":"D"}
print(dic)
print(dic["LUNES"])

#LONGITUD DEL DIC
len(dic)
print("La longitud del diccionario es:",len(dic))









Valor
{'Llave': 'Valor'}
{'LUNES': 'L', 'MARTES': 'M', 'MIÉRCOLES': 'MM', 'JUEVES': 'J', 'VIERNES': 'V', 'SÁBADO': 'S', 'DOMINGO': 'D'}
L
La longitud del diccionario es: 7


EJERCICIO 1.44 PDF PROVINCIAS Y CAPITALES

In [ ]:

#EJERCICIO 1.44 PDF PROVINCIAS Y CAPITALES

#Generar para cada provincia una tupla con el
#nombre de la provincia, su capital, su población
#y su PBI.
#Armar un diccionario donde cada valor sea la
#tupla de una provincia y la claves sea el
#nombre de la provincia.
#Mostrar para cada provincia su capital




Tabla Agraria

In [2]:
import numpy as np
import matplotlib as lpt
import pandas as pd

df = pd.read_csv("tabla_agraria.csv")
df



Etiquetas de fila  HAS SEMBRADAS trigo  RINDE ESTIMADO  \
0           CONDORI,ALICIA ADELINA               1199.0           735.0   
1       BONGIOVANNI, GERARDO PEDRO                 60.0            40.0   
2         BRIZZOLA, GERARDO MIGUEL                 80.0            40.0   
3             CAON, DANIEL ANTONIO                  NaN             NaN   
4               CASALI, JORGE LUIS                 23.0            40.0   
5        CASTAGNO, RICARDO EDMUNDO                 20.0            40.0   
6          CESCHINI, ALDO Y MIGUEL                 50.0            30.0   
7           CESCHINI, MIGUEL ANGEL                 20.0            35.0   
8             COMPANIA DAB S.R.L.-                 20.0            30.0   
9          DROVETTA, GERARDO MARIO                 35.0            30.0   
10          FERNANDEZ, JULIO CESAR                  NaN             NaN   
11               FERNANDEZ, MARCOS                  NaN             NaN   
12            GALLI, CESAR ENRIQUE                 60.0            30.0   
13           GAMBINI, EDGARDO ALDO                 17.0            40.0   
14         GAMBINI, RUBEN NORBERTO                 17.0            40.0   
15         Gentile, Alejandro Jose                 15.0            40.0   
16  LOPEZ MIGUEL A.-LOPEZ JORGE A.                 36.0            30.0   
17          Losada, Gustavo Adolfo                 20.0            30.0   
18         MIGNACCO, OSCAR ALBERTO                149.0            35.0   
19        MONSERRAT, MARCO ANTONIO                 17.0            40.0   
20         PASCHETTA, SANDRA MARIA                400.0            30.0   
21            PIPINO HERMANOS S.S.                 39.0            40.0   
22           SARINA, CARLOS DANIEL                 38.0            35.0   
23    SUC DE CARLETTI, ATILIO JUAN                 43.0            30.0   
24            VERON ALDO Y ALBERTO                 40.0            30.0   

    PRODUCCION  OBJETIVO ACOPIO  TN OBJETIVO ACOPIO  Suma de acopio real   \
0       3988.5           1700.0             2147.05              2366.212   
1        240.0             50.0              120.00               202.391   
2        320.0              0.0                0.00               283.687   
3          NaN              NaN                 NaN               154.834   
4         92.0            100.0               92.00                66.042   
5         80.0            100.0               80.00                   NaN   
6        150.0             70.0              105.00                21.116   
7         70.0            100.0               70.00                30.947   
8         60.0             50.0               30.00                   NaN   
9        105.0            100.0              105.00                74.116   
10         NaN              NaN                 NaN                34.390   
11         NaN              NaN                 NaN                82.920   
12       180.0             50.0               90.00               121.555   
13        68.0            100.0               68.00                50.189   
14        68.0            100.0               68.00                59.062   
15        60.0            100.0               60.00                61.415   
16       108.0            100.0              108.00               113.599   
17        60.0            100.0               60.00                75.554   
18       521.5             70.0              365.05               421.753   
19        68.0            100.0               68.00                17.408   
20      1200.0             10.0              120.00               271.761   
21       156.0            100.0              156.00                   NaN   
22       133.0            100.0              133.00                11.824   
23       129.0            100.0              129.00               136.097   
24       120.0            100.0              120.00                75.552   

    Unnamed: 7  
0          NaN  
1          NaN  
2          N

Tabla Médica

In [ ]:

import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

# Cargar el dataset

cancer = load_breast_cancer()
data = pd.DataFrame(data=cancer.data, columns=cancer.feature_names)
# Asignar la columna de clase correctamente
data['target'] = cancer.target

# Recuento de clases antes del mapeo
class_counts = data['target'].value_counts()
print("Recuento de clases antes del mapeo:")
print(class_counts)

# Crear una lista para almacenar los valores de target
target_list = list(data["target"])  # Forma más eficiente de obtener los valores

print(target_list[:10])  # Mostrar los primeros 10 valores




Recuento de clases antes del mapeo:
target
1    357
0    212
Name: count, dtype: int64
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
